# Generated by Django 4.2.7 on 2023-11-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
