# Generated by Django 4.2.7 on 2023-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=1000)),
                ('job_content', models.TextField()),
                ('job_url', models.URLField()),
            ],
        ),
    ]
