# Generated by Django 4.2.7 on 2023-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='job_content',
            field=models.TextField(unique=True),
        ),
    ]
